version: '3.8'

services:
  rasa_base:
    build:
      context: .
      dockerfile: dockerfile
    image: rasa_base  # Unified image for rasa and actions
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app

  rasa:
    image: rasa_base
    container_name: rasa_server
    ports:
      - "5005:5005"
    depends_on:
      - actions
    command: rasa run --enable-api --cors "*"
    restart: unless-stopped

  actions:
    image: rasa_base
    container_name: rasa_actions
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions  # Restrict volume to actions only
    depends_on:
      - llama_index_api
    command: rasa run actions
    env_file:
      - .env
    restart: unless-stopped

  llama_index_api:
    build:
      context: ./llamaindex_api
      dockerfile: dockerfile
    container_name: llama_index_api
    ports:
      - "8000:8000"
    volumes:
      - ./Tunisia_Data:/app/Tunisia_Data
      - ./storage/cache:/app/storage/cache
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    restart: unless-stopped
